name: Flutter release

on: [push]

jobs:
   build:
     name: Test, build and release
     runs-on: ubuntu-latest
     steps:
        - name: Git clone
          uses: actions/checkout@v1
        - name: Start SSH session
          run: ./test
