name: Flutter release

on: [push]

jobs:
   build:
     name: Test, build and release
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/setup-java@v3
       with:
        distribution: 'zulu'
        java-version: '17'
     - name: Download Files
       run:  | 
          wget https://webwerks.dl.sourceforge.net/project/pixelos-releases/twelve/gauguin/PixelOS_gauguin-12.1-20220618-1105.zip
     - name: Upload to release
       uses: softprops/action-gh-release@v1
       with:
         files: PixelOS_gauguin-12.1-20220618-1105.zip
