name: Flutter release

on: [push]

jobs:
   build:
     name: Test, build and release
     runs-on: ubuntu-latest
     steps:
      - name: Start SSH via ngrok
        uses: P3TERX/ssh2actions@main
        env:
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
