name: Flutter release

on: [push]

jobs:
   build:
     name: Test, build and release
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/setup-java@v3
       with:
        distribution: 'zulu'
        java-version: '17'
     - name: Download Files
       run:  | 
         wget https://github.com/revanced/revanced-cli/releases/download/v2.5.3/revanced-cli-2.5.3-all.jar
         wget https://github.com/revanced/revanced-patches/releases/download/v2.13.3/revanced-patches-2.13.3.jar
         wget https://github.com/revanced/revanced-integrations/releases/download/v0.23.0/app-release-unsigned.apk
         wget https://r-static-assets.androidapks.com/rdata/1728e9cfac37e76233e07bfa38d31fc6/com.google.android.youtube_v17.26.35-1530256832_Android-6.0.apk
     - name: Build apk
       run: | 
         java -jar revanced-cli-2.5.3-all.jar -a com.google.android.youtube_v17.26.35-1530256832_Android-6.0.apk -b revanced-patches-2.13.3.jar -e disable-create-button -e hide-shorts-button -e hide-cast-button -e premium-heading -m app-release-unsigned.apk -c -o ytrevanced.apk
     - name: Upload file
       run: curl --upload-file ./ytrevanced.apk https://free.keep.sh
